---
# tasks file for ansible-role-fleet-key-pairs
- name: Ensure config directory exists
  ansible.builtin.file:
    path: "{{ ssh_config_path }}"
    state: directory

- name: Ensure config files exists
  ansible.builtin.file:
    path:  "{{ item }}"
    state: touch
  with_items:
    - "{{ ssh_config_path }}/config.p3r"
    - "{{ ssh_config_path }}/source.p3r"

- name: Ensure environment directories exist
  ansible.builtin.file:
    path: "{{ ssh_key_path }}/{{ item.environment }}"
    state: directory
  when: item.state == "present"
  with_items: "{{ p3r_input }}"