---
- name: Check if key exists
  stat:
    path: "{{ ssh_key_path }}/{{ item.environment }}/{{ item.ssh_key_domain }}/{{ item.ssh_service }}_{{ item.ssh_key_type }}"
  when: item.state == "absent"
  with_items: "{{ p3r_input }}"
  register: key_existed

- name: Remove public key from directory
  ansible.builtin.file:
    path: "{{ ssh_key_path }}/{{ item.environment }}/{{ item.ssh_key_domain }}/{{ item.ssh_service }}_{{ item.ssh_key_type }}.pub"
    state: absent
  when: item.state == "absent"
  with_items: "{{ p3r_input }}"

- name: Remove private key from directory
  ansible.builtin.file:
    path: "{{ ssh_key_path }}/{{ item.environment }}/{{ item.ssh_key_domain }}/{{ item.ssh_service }}_{{ item.ssh_key_type }}"
    state: absent
  when: item.state == "absent"
  with_items: "{{ p3r_input }}"

  